source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AnimateModal_Example', :exclusive => true do
  pod "AnimateModal", :path => "../"
end

target 'AnimateModal_Tests', :exclusive => true do
  pod "AnimateModal", :path => "../"

  
end
